"""Test plan routes — generate, list, edit, approve.

Plans are generated by Claude reasoning over the project's screen graph + a
feature description. The Telegram bot's /uat command also calls this endpoint.
"""
from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from webapp.api import models, schemas
from webapp.api.db import get_db
from webapp.api.services.test_planner import generate_test_plan

logger = logging.getLogger(__name__)

router = APIRouter(tags=["plans"])


@router.get("/api/projects/{project_id}/plans", response_model=list[schemas.TestPlanOut])
def list_plans(project_id: int, db: Session = Depends(get_db)):
    plans = (
        db.query(models.TestPlan)
        .filter(models.TestPlan.project_id == project_id)
        .order_by(models.TestPlan.created_at.desc())
        .all()
    )
    return plans


@router.post(
    "/api/projects/{project_id}/plans",
    response_model=schemas.TestPlanOut,
    status_code=201,
)
def create_plan(
    project_id: int,
    payload: schemas.TestPlanCreate,
    db: Session = Depends(get_db),
):
    """Generate a test plan from a feature description.

    Reads all screens + edges for the project, asks Claude to enumerate
    test cases, and persists them in draft status for review.
    """
    project = db.get(models.Project, project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    screens = (
        db.query(models.Screen).filter(models.Screen.project_id == project_id).all()
    )
    if not screens:
        raise HTTPException(
            status_code=400,
            detail="Cannot generate a plan: no screens uploaded yet for this project.",
        )
    edges = db.query(models.Edge).filter(models.Edge.project_id == project_id).all()

    screens_data = [
        {
            "id": s.id,
            "name": s.name,
            "display_name": s.display_name,
            "purpose": s.purpose,
        }
        for s in screens
    ]
    edges_data = [
        {
            "from_screen_id": e.from_screen_id,
            "to_screen_id": e.to_screen_id,
            "trigger": e.trigger,
        }
        for e in edges
    ]

    cases = generate_test_plan(
        feature_description=payload.feature_description,
        screens=screens_data,
        edges=edges_data,
    )

    plan = models.TestPlan(
        project_id=project_id,
        feature_description=payload.feature_description,
        voice_transcript=payload.voice_transcript,
        status="draft",
    )
    db.add(plan)
    db.flush()  # get plan.id without commit

    name_to_id = {s.name: s.id for s in screens}
    for c in cases:
        target_name = c.get("target_screen_name")
        target_id = name_to_id.get(target_name)
        case = models.TestCase(
            plan_id=plan.id,
            title=c.get("title", "Untitled case"),
            target_screen_id=target_id,
            navigation_path=c.get("navigation_path"),
            acceptance_criteria=c.get("acceptance_criteria", ""),
            branch_label=c.get("branch_label"),
            status="proposed",
        )
        db.add(case)

    db.commit()
    db.refresh(plan)
    logger.info(f"[plans] Generated {len(cases)} cases for project {project_id} plan {plan.id}")
    return plan


@router.get("/api/plans/{plan_id}", response_model=schemas.TestPlanOut)
def get_plan(plan_id: int, db: Session = Depends(get_db)):
    plan = db.get(models.TestPlan, plan_id)
    if not plan:
        raise HTTPException(status_code=404, detail="Plan not found")
    return plan


@router.patch("/api/plans/{plan_id}", response_model=schemas.TestPlanOut)
def update_plan(plan_id: int, status: str, db: Session = Depends(get_db)):
    plan = db.get(models.TestPlan, plan_id)
    if not plan:
        raise HTTPException(status_code=404, detail="Plan not found")
    if status not in {"draft", "approved"}:
        raise HTTPException(status_code=400, detail="status must be 'draft' or 'approved'")
    plan.status = status
    db.commit()
    db.refresh(plan)
    return plan


@router.patch("/api/cases/{case_id}", response_model=schemas.TestCaseOut)
def update_case(
    case_id: int,
    payload: schemas.TestCaseUpdate,
    db: Session = Depends(get_db),
):
    case = db.get(models.TestCase, case_id)
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    for field, value in payload.model_dump(exclude_unset=True).items():
        setattr(case, field, value)
    db.commit()
    db.refresh(case)
    return case


@router.delete("/api/cases/{case_id}", status_code=204)
def delete_case(case_id: int, db: Session = Depends(get_db)):
    case = db.get(models.TestCase, case_id)
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")
    db.delete(case)
    db.commit()
